const animales = [

  { numero: "0", animal: "DELFÍN" },
  { numero: "00", animal: "BALLENA" },

  { numero: "01", animal: "CARNERO" },
  { numero: "02", animal: "TORO" },
  { numero: "03", animal: "CIEMPIÉS" },
  { numero: "04", animal: "ALACRÁN" },
  { numero: "05", animal: "LEÓN" },
  { numero: "06", animal: "RANA" },
  { numero: "07", animal: "PERICO" },
  { numero: "08", animal: "RATÓN" },
  { numero: "09", animal: "ÁGUILA" },

  { numero: "10", animal: "TIGRE" },
  { numero: "11", animal: "GATO" },
  { numero: "12", animal: "CABALLO" },
  { numero: "13", animal: "MONO" },
  { numero: "14", animal: "PALOMA" },
  { numero: "15", animal: "ZORRO" },
  { numero: "16", animal: "OSO" },
  { numero: "17", animal: "PAVO" },
  { numero: "18", animal: "BURRO" },
  { numero: "19", animal: "CHIVO" },

  { numero: "20", animal: "COCHINO" },
  { numero: "21", animal: "GALLO" },
  { numero: "22", animal: "CAMELLO" },
  { numero: "23", animal: "CEBRA" },
  { numero: "24", animal: "IGUANA" },
  { numero: "25", animal: "GALLINA" },
  { numero: "26", animal: "VACA" },
  { numero: "27", animal: "PERRO" },
  { numero: "28", animal: "ZAMURO" },
  { numero: "29", animal: "ELEFANTE" },

  { numero: "30", animal: "CAIMÁN" },
  { numero: "31", animal: "LAPA" },
  { numero: "32", animal: "ARDILLA" },
  { numero: "33", animal: "PESCADO" },
  { numero: "34", animal: "VENADO" },
  { numero: "35", animal: "JIRAFA" },
  { numero: "36", animal: "CULEBRA" },
  { numero: "37", animal: "TORTUGA" },
  { numero: "38", animal: "BÚFALO" },
  { numero: "39", animal: "LECHUZA" },

  { numero: "40", animal: "AVISPA" },
  { numero: "41", animal: "CANGURO" },
  { numero: "42", animal: "TUCÁN" },
  { numero: "43", animal: "MARIPOSA" },
  { numero: "44", animal: "CHIGÜIRE" },
  { numero: "45", animal: "GARZA" },
  { numero: "46", animal: "PUMA" },
  { numero: "47", animal: "PAVO REAL" },
  { numero: "48", animal: "PUERCOESPÍN" },
  { numero: "49", animal: "PEREZA" },

  { numero: "50", animal: "CANARIO" },
  { numero: "51", animal: "PELÍCANO" },
  { numero: "52", animal: "PULPO" },
  { numero: "53", animal: "CARACOL" },
  { numero: "54", animal: "GRILLO" },
  { numero: "55", animal: "OSO HORMIGUERO" },
  { numero: "56", animal: "TIBURÓN" },
  { numero: "57", animal: "PATO" },
  { numero: "58", animal: "HORMIGA" },
  { numero: "59", animal: "PANTERA" },

  { numero: "60", animal: "CAMALEÓN" },
  { numero: "61", animal: "PANDA" },
  { numero: "62", animal: "CACHICAMO" },
  { numero: "63", animal: "CANGREJO" },
  { numero: "64", animal: "GAVILÁN" },
  { numero: "65", animal: "ARAÑA" },
  { numero: "66", animal: "LOBO" },
  { numero: "67", animal: "AVESTRUZ" },
  { numero: "68", animal: "JAGUAR" },
  { numero: "69", animal: "CONEJO" },

  { numero: "70", animal: "BISONTE" },
  { numero: "71", animal: "GUACAMAYA" },
  { numero: "72", animal: "GORILA" },
  { numero: "73", animal: "HIPOPÓTAMO" },
  { numero: "74", animal: "TURPIAL" },
  { numero: "75", animal: "GUÁCHARO" }

];
